server:
  port: 8081
#jdbc数据库连接参数
spring:
  datasource:
    url: jdbc:mysql://172.17.28.129:3306/P365MyTest
    username: root
    password: Arcsoft01
  application:
    name: user-service
#mybatis配置
mybatis:
  configuration:
    #驼峰命名开启 通用mapper中默认设置了为true，因此这里可以不用设置了
    #map-underscore-to-camel-case: true
    #别名包路径配置
    type-aliases-package: cn.itcast.user.pojo

#  mapper-locations: mapper/*.xml
eureka:
  client:
    service-url:
      #当eureka是集群时，这里要配置多个
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  #写死服务地址， 在本地调试时，如果电脑联网，在消费放获取到的host无法访问到服务提供者
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1