server:
  port: 8088
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      #多个用逗号分隔http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
      defaultZone: http://127.0.0.1:10086/eureka
    #拉取服务周期5s
    registry-fetch-interval-seconds: 3
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
#开启feign熔断服务
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/html,application/xml,application/json   #设置压缩的数据类型
      min-request-size: 2048 #设置触发压缩的大小下限

#ribbon的超时时长配置
ribbon:
  ConnectionTimeOut: 500  #如果500ms没有建立连接就会抛出异常
  ReadTimeOut: 2000 #如果建立了连接2s内没有返回抛出异常

#为user-service 设置负载均衡策略，默认为轮训策略
user-service:
  ribbon:
    NFLoadBalanceRuleClassName: com.netflix.loadbalancer.RandomRule

#为所有方法设置超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    #给user-service服务设置
    user-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
